json.id room.id
json.user_id room.user_id
json.address room.address
json.city room.city
json.state room.state
json.price room.price
json.description room.description
json.home_type room.home_type
json.room_type room.room_type
json.total_occupancy room.total_occupancy
json.total_bedrooms room.total_bedrooms
json.total_bathrooms room.total_bathrooms
json.room_images room.room_images
json.created_at room.created_at
json.updated_at room.updated_at